# Generated by Django 6.1.1 on 2026-09-30 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название торта')),
                ('base_diameter', models.PositiveIntegerField(default=18, verbose_name='Базовый диаметр (см)')),
                ('description', models.TextField(blank=True, verbose_name='Этапы приготовления / Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена закупки')),
                ('package_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество в упаковке')),
                ('unit', models.CharField(choices=[('g', 'Граммы (г)'), ('ml', 'Миллилитры (мл)'), ('pcs', 'Штуки (шт)')], default='g', max_length=5, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='CakeDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название декора/упаковки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to='core.cake')),
            ],
        ),
        migrations.CreateModel(
            name='CakeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество в базовом рецепте')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_ingredients', to='core.cake')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
            options={
                'unique_together': {('cake', 'ingredient')},
            },
        ),
    ]
