# Generated by Django 6.1.1 on 2026-10-03 00:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cakeingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cake',
            name='bake_loss_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.90'), max_digits=4, verbose_name='Коэфф. выхода с учетом упёка'),
        ),
        migrations.AddField(
            model_name='cake',
            name='labor_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Наценка за работу (1.0 = +100%)'),
        ),
        migrations.AddField(
            model_name='cakeingredient',
            name='component',
            field=models.CharField(choices=[('biscuit', 'Бисквит'), ('cream', 'Крем / Прослойка'), ('filling', 'Начинка / Конфи'), ('soak', 'Пропитка'), ('coating', 'Выравнивание (ганаш/крем-чиз)'), ('decor', 'Декор')], default='biscuit', max_length=20, verbose_name='Слой / назначение'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(blank=True, verbose_name='Этапы приготовления'),
        ),
        migrations.AlterField(
            model_name='cakeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество на базовый диаметр'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='package_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фасовка упаковки'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'г'), ('ml', 'мл'), ('pcs', 'шт')], default='g', max_length=5, verbose_name='Ед. изм.'),
        ),
        migrations.CreateModel(
            name='PackagingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование (Коробка, Подложка и т.д.)')),
                ('quantity', models.DecimalField(decimal_places=1, default=1.0, max_digits=6, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_items', to='core.cake')),
            ],
        ),
        migrations.DeleteModel(
            name='CakeDecoration',
        ),
    ]
